# Generated by Django 3.2.5 on 2021-07-21 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devtoolBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devtool',
            old_name='explanation',
            new_name='description',
        ),
    ]
