# Generated by Django 3.2.5 on 2021-07-21 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devtoolBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='idea_image/%Y/%m/%d')),
                ('content', models.TextField()),
                ('interest', models.IntegerField(default=0)),
                ('devtool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devtoolBlog.devtool')),
            ],
        ),
    ]
