# Generated by Django 3.2.5 on 2021-07-21 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideaBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='name',
            new_name='title',
        ),
    ]
